### ISSUE TITLE
Fix for /var content (ostreedev PR #569) doesn't seem to be in the latest centos-bootc-dev base image

### ISSUE THREAD

**Issue by nzwulfin** [CentOS/centos-bootc#140] opened 2024-01-16 21:59 UTC
Intalling Postgres in the latest centos-bootc-dev base container fails on the ostree commit due to content being placed in /var/lib by the rpm install.  This container should include the code from [ostreedev PR #569](https://github.com/ostreedev/ostree-rs-ext/pull/569)

Error from podman build:
```
STEP 3/3: RUn ostree container commit
Found file: var/lib/pgsql/.bash_profile
error: Found content in var
Error: building at STEP "RUN ostree container commit": while running runtime: exit status 1
```

Simple containerfile to reproduce

```
FROM quay.io/centos-bootc/centos-bootc-dev:stream9

RUN dnf install -y postgresql-server && \
    rm /var/log/*.log /var/lib/dnf -rf

RUN ostree container commit

```
Output of podman images
`quay.io/centos-bootc/centos-bootc-dev  stream9     96188766724f  About an hour ago  1.45 GB`

ostree info from inside container:
bash-5.1# ostree --version
```
libostree:
 Version: '2023.9'
 Git: f9d013632d88db3a2a89a8c4924417b3cfbdabec
 DevelBuild: yes
 Features:
  - inode64
  - libcurl
  - gpgme
  - composefs
  - ex-fsverity
  - libarchive
  - selinux
  - openssl
  - sign-ed25519
  - libmount
  - systemd
  - devel
  - p2p

bash-5.1# rpm -qa | grep ostree
ostree-libs-2023.8.54.g19cd8cf1-%autorelease.x86_64
ostree-2023.8.54.g19cd8cf1-%autorelease.x86_64
rpm-ostree-libs-2024.1.23.gefe57a65-1.el9.x86_64
rpm-ostree-2024.1.23.gefe57a65-1.el9.x86_64

```

**Comment by cgwalters** [comment] 2024-01-17 16:22
The short version is you can just drop `RUN ostree container commit`.  We aren't trying to do anything really important there anymore because basically no one ever used it correctly, it has hard to explain semantics, and we are just going to try harder to Just Work with whatever's in the container image.

Just did https://github.com/ostreedev/ostree-rs-ext/pull/584 to fully codify this.

**Comment by nzwulfin** [comment] 2024-01-17 18:12
Removed the ostree commit, everything built fine, can start / stop / modify the running container, including more changes to /var once running.  Thanks!

**Comment by cgwalters** [comment] 2024-02-06 22:34
We need to try to re-land https://github.com/CentOS/centos-bootc/pull/186 again, once https://github.com/osbuild/bootc-image-builder/issues/18 is fixed

**Comment by cgwalters** [comment] 2024-02-06 23:46
That's a related problem, but the real issue here is that the change in https://github.com/ostreedev/ostree/pull/3103 doesn't work on c9s because systemd there doesn't understand `C+`, so it degrades to `C` which is just a no-op because `/var` already exists.

Probably the simplest thing is to change ostree-ext to synthesize tmpfiles.d snippets instead, i.e. instead of a global `/var` we introduce `/usr/share/container-image-var` or so, and our tmpfiles.d snippets target subdirectories of it.  (And ideally, we avoid generating duplicate tmpfiles.d entries, but that's its own complex mess)

This would also fix a cosmetic issue of a conflict between our `/usr/share/factory/var` and `/usr/lib/tmpfiles.d/var.conf` from systemd, but that's currently just a warning because the ostree one wins.

**Comment by cgwalters** [comment] 2024-02-13 15:09
OK, I've verified that with the latest changes from https://github.com/ostreedev/ostree/pull/3166 and https://github.com/ostreedev/ostree-rs-ext/pull/602 that have now landed in [the latest dev image](https://github.com/CentOS/centos-bootc-dev) [a stock httpd example](https://gitlab.com/bootc-org/tests/container-fixtures/-/blob/main/stock-httpd/Containerfile) works when run through bib.

**Comment by nzwulfin** [comment] 2024-02-13 21:00
Local testing on the reproducer works great, thanks!

**Comment by cgwalters** [comment] 2024-02-13 22:18
Thanks so much for testing this!

**Comment by nzwulfin** [comment] 2024-02-15 18:52
From reading the linked PRs I think i see what's happening but not why.  In the base image,` /var/run` is properly symlinked to` /run` based on `/usr/lib/tmpfiles.d/var.conf`, but in the derived image it's a regular directory.

```
[core@bootc-builder repro]$ podman exec -it base ls -ald /var/run
lrwxrwxrwx. 1 root root 6 Feb 15 18:30 /var/run -> ../run
[core@bootc-builder repro]$ podman exec -it repro ls -ald /var/run
drwxr-xr-x. 1 root root 22 Feb 15 18:26 /var/run
```

There's a tmpfile.d config that creates the directory for postgresql:
`d /run/postgresql 0755 postgres postgres -`

Looks like the tmpfile definition for postgres is interfering with the `/var/run` definition in var.conf?

**Comment by cgwalters** [comment] 2024-02-15 19:05
Hmm not having `/var/run` be a symlink is indeed going to cause a lot of problems.  

And yep, I see `dnf -y install postgresql-server` causes this.  It should be easy to work around this with a `RUN rm /var/run -rf`. 

And yep I see, the problem is that the RPM includes `/var/run/postgresql` as physical content.  This is a serious bug in the package.

**Comment by cgwalters** [comment] 2024-02-15 19:09
https://issues.redhat.com/browse/RHEL-25756

**Comment by cgwalters** [comment] 2024-02-15 19:12
https://gitlab.com/bootc-org/tests/container-fixtures/-/merge_requests/3

**Comment by nzwulfin** [comment] 2024-02-15 19:16
I looked for it in the rpm file list first and missed it somehow.. oh well :)

Tested the postgresql reproducer with the suggested workaround and it works as it should.  The tmpfile.d config shipped in the package works, and /var/run is properly linked.

**Comment by cgwalters** [comment] 2024-02-16 15:50
I believe we've done everything we can do in the base image for this issue now.

**Closed by cgwalters** 2024-02-16 15:50 UTC

**Comment by cgwalters** [comment] 2024-03-20 20:44
:arrow_right: https://github.com/CentOS/centos-bootc/issues/354#issuecomment-2010590564
